- name: dk-search-tests
  description: Deployment of search-tests application using DK IaC and DK CICD
  build:
    provider: dkcicd
    pipelines:
    - name: application-build-v1
      parameters:
        acronym: search-tests
        applicationName: search-tests
        applicationType: k8s
        baseBranch: setup/dk-kubernetes
        chartName: sre-provisioning
        dockerfilePath: Dockerfile
        environmentType: stable
        imageRepo: vtex/search-tests
        imageTag: '{{ ref_name }}'
        rollout: "true"
      when:
      - event: push
        source: tag
        regex: ^((?!beta).)*$
      runtime:
        architecture: amd64
    - name: application-deploy-v2
      parameters:
        acronym: search-tests
        baseBranch: setup/dk-kubernetes
        projectName: sre-apps
      when:
      - event: push
        source: branch
        regex: setup/dk-kubernetes
      runtime:
        architecture: amd64
