kubernetes:
  base:
    repoName: search-tests
    imageRepository: 053131491888.dkr.ecr.us-east-1.amazonaws.com
    environment: stable
  apps:
    - name: search-tests
      dockerfile: Dockerfile
      imageRepoName: vtex/search-tests
      affinity:
        type: required
        conditions:
          - key: eks.amazonaws.com/nodegroup
            value: EKS-Robots-Spot-Workers
      secretsManager:
        enabled: true
      kind: cronjob
      schedule: "*/10 * * * *"
      resources:
        limits:
          cpu: 800m
          memory: 1500Mi
        requests:
          cpu: 400m
          memory: 1000Mi
