kubernetes:
  base:
    repoName: search-tests
    imageRepository: 053131491888.dkr.ecr.us-east-1.amazonaws.com
    environment: stable
  apps:
    - name: search-tests
      dockerfile: Dockerfile
      imageRepoName: vtex/search-tests
      secretsManager:
        enabled: true
      kind: cronjob
      schedule: "* * * * *"
      resources:
        limits:
          cpu: 400m
          memory: 800Mi
        requests:
          cpu: 200m
          memory: 400Mi
