---
kind: pipeline
type: kubernetes
name: Continuous Deployment
steps:
  - name: Build and publish image to ECR
    image: 053131491888.dkr.ecr.us-east-1.amazonaws.com/vtex/drone-builder:latest
    pull: always
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID:
        from_secret: 053131491888_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: 053131491888_AWS_SECRET_ACCESS_KEY
      GIT_TOKEN:
        from_secret: GIT_TOKEN
      GIT_USER_NAME: ${DRONE_COMMIT_AUTHOR_NAME}
      GIT_USER_EMAIL: ${DRONE_COMMIT_AUTHOR_EMAIL}
      DOCKER_REGISTRY: 053131491888.dkr.ecr.us-east-1.amazonaws.com
      ENVIRONMENT: stable
    commands:
      - python3 /app/toolbelt/main.py
    volumes:
      - name: dockersock
        path: /var/run
volumes:
  - name: dockersock
    host:
      path: /var/run/
trigger:
  branch:
    - main
